#!/bin/bash

if [ -z "$1" ]; then
    dir=/home/$USER
else
    dir=$1
fi

selected=$(fd . "$dir" | rofi -dmenu -i -p "Search for files" -fullscreen)


if [[ -z $selected ]]; then
    exit
fi
lastchar="${selected: -1}"

if [[ $lastchar == "+" ]] ; then 
    # remove the trailing character
    selected=${selected: : -1}

    # show the selected file in the file manager
    dolphin --select "$selected"

elif [[ $lastchar == "<" ]]; then
    # copy path to clipboard
    selected=${selected: : -1}
    echo "$selected" |  xclip -sel clip

elif [[ $lastchar == "@" ]]; then
    selected=${selected: : -1}
    # copy to clipboard
    xsel -b < "$selected"
else
    if [ -d "$selected" ]; then
        # if it's a directory, open it with dolphin
        dolphin "$selected"
    else
        # otherwise use the default application
        xdg-open "$selected"
    fi
fi
